version: "3.8"

services:
  api:
    build: ./
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - ACCESS_TOKEN_SECRET=1234
      - REFRESH_TOKEN_SECRET=12345
      - DB_HOSTNAME=db
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    # environment:
    #   - POSTGRES_PASSWORD=password
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - productivity-node:/var/lib/postgresql/data

volumes:
  productivity-node:
